apiVersion: v1
kind: Secret

metadata:
  name: bus-booking-secret

type: Opaque

stringData:
  DB_USER: your-db-user
  DB_PASSWORD: your-db-password
  EMAIL_USER: your-email@gmail.com
  EMAIL_PASSWORD: your-app-password
