apiVersion: v1
kind: Secret
metadata:
  name: bus-booking-secret

type: Opaque

stringData:
  DB_USER: admink
  DB_PASSWORD: Kiran123!
  EMAIL_USER: mybusbookingapp@gmail.com
  EMAIL_PASSWORD: cxwwqirelqvbnsmn
